[package]
name = "term_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linereader = "0.4"
miniserde = "0.1"
owo-colors = "3.4"